services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: polewindb
      POSTGRES_USER: polewin
      POSTGRES_PASSWORD: polewin
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - polewin_pgdata:/var/lib/postgresql/data

volumes:
  polewin_pgdata:
