export interface Tech {
    name: string;
    icon: string;
    version: string;
    tags: string[];
    short: string;
    desc: string;
}

export const TECHS: Tech[] = [
    {
        name: "express",
        icon: "⚡",
        version: "^5.2.1",
        tags: ["core"],
        short: "Framework web minimaliste pour Node.js",
        desc: "Express 5 est le framework HTTP de référence pour Node.js. Il orchestre le routing, les middlewares en chaîne et la gestion des erreurs async. La v5 supporte nativement async/await dans les route handlers, ce qui élimine le besoin de try/catch manuels sur chaque route.",
    },
    {
        name: "typescript",
        icon: "🔷",
        version: "^5.9.3",
        tags: ["core", "dev"],
        short: "Superset typé de JavaScript",
        desc: "TypeScript ajoute un système de types statiques à JavaScript. Il détecte les erreurs au compile-time plutôt qu'à l'exécution, améliore l'autocomplétion IDE et rend le code plus maintenable. Indispensable pour les projets d'équipe et les APIs publiques.",
    },
    {
        name: "sequelize",
        icon: "🗄️",
        version: "^6.37.7",
        tags: ["database"],
        short: "ORM PostgreSQL/multi-dialecte pour Node.js",
        desc: "Sequelize abstrait les requêtes SQL via des modèles JavaScript. Il gère les associations, les hooks de cycle de vie, les transactions et les migrations. Permet d'écrire la logique métier sans SQL brut, avec validation de schéma intégrée.",
    },
    {
        name: "pg",
        icon: "🐘",
        version: "^8.16.3",
        tags: ["database"],
        short: "Client PostgreSQL natif pour Node.js",
        desc: "Driver officiel PostgreSQL pour Node.js. C'est la couche basse sur laquelle Sequelize s'appuie pour exécuter les requêtes. Il gère le pool de connexions, les prepared statements, les types natifs PostgreSQL et les transactions.",
    },
    {
        name: "pg-hstore",
        icon: "🔄",
        version: "^2.3.4",
        tags: ["database"],
        short: "Sérialisation du type hstore PostgreSQL",
        desc: "Utilitaire requis par Sequelize avec PostgreSQL. Il sérialise et désérialise le type de données hstore (paires clé-valeur) de PostgreSQL en objets JavaScript. Dépendance implicite obligatoire dès qu'on utilise Sequelize + PostgreSQL.",
    },
    {
        name: "umzug",
        icon: "📦",
        version: "^3.8.2",
        tags: ["database"],
        short: "Gestionnaire de migrations programmatiques",
        desc: "Umzug est un moteur de migrations agnostique qui s'intègre à Sequelize. Il suit l'état des migrations appliquées (up/down), gère le versioning du schéma DB et permet d'écrire les migrations en TypeScript. Alternative plus flexible à sequelize-cli.",
    },
    {
        name: "helmet",
        icon: "🛡️",
        version: "^8.1.0",
        tags: ["security"],
        short: "Headers HTTP de sécurité automatiques",
        desc: "Helmet active automatiquement une dizaine de headers HTTP de sécurité : Content-Security-Policy (contre les injections XSS), X-Frame-Options (contre le clickjacking), Strict-Transport-Security (HTTPS forcé), X-Content-Type-Options (MIME sniffing), etc. Un must-have absolu en production.",
    },
    {
        name: "express-rate-limit",
        icon: "🚦",
        version: "^8.2.1",
        tags: ["security"],
        short: "Rate limiting contre le brute force et les abus",
        desc: "Middleware qui plafonne le nombre de requêtes par IP sur une fenêtre de temps glissante. Configuré ici à deux niveaux : authLimiter (10 req/15 min) sur /auth/register et /auth/login pour bloquer les attaques brute force, et apiLimiter (200 req/15 min) sur tout /api/v1.",
    },
    {
        name: "jsonwebtoken",
        icon: "🔑",
        version: "^9.0.3",
        tags: ["security"],
        short: "Authentification stateless par JSON Web Tokens",
        desc: "Implémentation des JWT (RFC 7519). Permet de créer des tokens signés avec une clé secrète, de les vérifier et de les décoder. Utilisé pour les access tokens (expiration 15 min) et les tokens de vérification email (24h). La clé secrète est validée par Zod au démarrage.",
    },
    {
        name: "argon2",
        icon: "🔐",
        version: "^0.44.0",
        tags: ["security"],
        short: "Hachage de mots de passe — standard OWASP",
        desc: "Argon2 est l'algorithme recommandé par l'OWASP et gagnant de la Password Hashing Competition 2015. Résistant aux attaques GPU et ASIC grâce à sa consommation mémoire configurable. Bien plus sécurisé que MD5, SHA ou bcrypt contre les attaques modernes.",
    },
    {
        name: "bcryptjs",
        icon: "🔒",
        version: "^3.0.3",
        tags: ["security"],
        short: "Hachage bcrypt en pur JavaScript",
        desc: "Implémentation pure JavaScript de bcrypt, sans dépendances natives compilées. Présent pour compatibilité ou fallback sur les environnements où argon2 ne peut pas compiler. bcrypt reste solide mais moins résistant aux attaques GPU modernes qu'argon2id.",
    },
    {
        name: "zod",
        icon: "✅",
        version: "^4.2.1",
        tags: ["security", "config"],
        short: "Validation de schémas TypeScript-first",
        desc: "Zod valide les données à l'exécution avec inférence de types TypeScript automatique — zéro duplication entre le schéma et les types. Utilisé à deux endroits clés : validation des variables d'environnement au démarrage (crash si JWT_SECRET manquant) et validation des corps de requêtes HTTP (DTOs).",
    },
    {
        name: "cors",
        icon: "🌐",
        version: "^2.8.5",
        tags: ["security"],
        short: "Contrôle des origines Cross-Origin (CORS)",
        desc: "Middleware Express qui configure les headers CORS pour restreindre quels domaines peuvent appeler l'API depuis un navigateur. L'origine autorisée est injectée via la variable CORS_ORIGIN dans l'environnement, ce qui permet des configs différentes en dev et prod.",
    },
    {
        name: "pino",
        icon: "📝",
        version: "^10.3.1",
        tags: ["logging"],
        short: "Logger JSON ultra-rapide pour Node.js",
        desc: "Pino est le logger le plus performant de l'écosystème Node.js — 5x plus rapide que Winston. Il produit des logs JSON structurés en production (facilement ingérés par Datadog, Grafana Loki, Elasticsearch) et des logs colorés en dev via pino-pretty. La structure JSON permet des requêtes précises sur les logs.",
    },
    {
        name: "pino-http",
        icon: "🌐",
        version: "^11.0.0",
        tags: ["logging"],
        short: "Middleware HTTP auto-logger pour Express",
        desc: "Middleware qui logue automatiquement chaque requête HTTP avec méthode, path, status code et durée de réponse. S'intègre à l'instance pino existante et enrichit chaque request avec un logger contextuel accessible via req.log pour des logs corrélés.",
    },
    {
        name: "pino-pretty",
        icon: "🎨",
        version: "^13.1.3",
        tags: ["logging", "dev"],
        short: "Formatage coloré des logs pino en développement",
        desc: "Transport pino qui reformate le JSON brut en sortie lisible et colorée pour les développeurs. Actif uniquement hors production (NODE_ENV !== production). En prod, les logs restent en JSON brut pour les outils de monitoring. Pas de surcoût en production.",
    },
    {
        name: "swagger-jsdoc",
        icon: "📖",
        version: "^6.2.8",
        tags: ["api"],
        short: "Génération OpenAPI depuis les commentaires JSDoc",
        desc: "Génère automatiquement une spécification OpenAPI 3.0 à partir des annotations @swagger dans les fichiers TypeScript. Permet de maintenir la documentation au plus près du code source et d'éviter la désynchronisation entre l'implémentation et la spec API.",
    },
    {
        name: "swagger-ui-express",
        icon: "🖥️",
        version: "^5.0.1",
        tags: ["api"],
        short: "Interface Swagger UI servie depuis Express",
        desc: "Sert l'interface graphique Swagger UI directement depuis Express sur /api/v1/docs. Permet d'explorer et de tester tous les endpoints de l'API depuis un navigateur sans outil externe (Postman, curl). Idéal pour les intégrations tierces et l'onboarding des développeurs.",
    },
    {
        name: "jest",
        icon: "🧪",
        version: "^30.2.0",
        tags: ["test"],
        short: "Framework de tests JavaScript tout-en-un",
        desc: "Jest est le framework de test standard pour Node.js et TypeScript. Il fournit assertions, mocks, spies, coverage et watch mode en un seul outil sans configuration complexe. Utilisé ici avec ts-jest (TypeScript natif) et supertest (tests HTTP d'intégration).",
    },
    {
        name: "supertest",
        icon: "🔬",
        version: "^7.2.2",
        tags: ["test"],
        short: "Tests d'intégration HTTP pour Express",
        desc: "Supertest permet d'envoyer de vraies requêtes HTTP à l'application Express dans les tests, sans démarrer le serveur sur un port réseau réel. Utilisé pour les tests d'intégration : health check, routes 404, headers de sécurité Helmet, format des réponses JSON.",
    },
    {
        name: "ts-jest",
        icon: "🔷",
        version: "^29.4.6",
        tags: ["test", "dev"],
        short: "Preset Jest pour TypeScript sans build step",
        desc: "ts-jest compile les fichiers TypeScript à la volée pour Jest, sans étape de build préalable. Permet d'écrire les tests directement en TypeScript avec tous les bénéfices du typage statique et des imports typés. Configuré via le preset ts-jest dans jest.config.js.",
    },
    {
        name: "dotenv",
        icon: "⚙️",
        version: "^17.2.3",
        tags: ["config"],
        short: "Chargement des variables d'environnement depuis .env",
        desc: "Charge le fichier .env dans process.env au démarrage. Incontournable pour séparer la configuration du code (principe 12-factor app). Utilisé conjointement avec Zod : dotenv charge les variables, Zod les valide et les convertit en types TypeScript.",
    },
    {
        name: "yamljs",
        icon: "📄",
        version: "^0.3.0",
        tags: ["config", "api"],
        short: "Parser YAML pour les specs OpenAPI",
        desc: "Librairie de parsing YAML utilisée pour lire les fichiers de configuration OpenAPI/Swagger au format .yaml. Permet de séparer la spec API dans des fichiers YAML lisibles plutôt que de tout définir en JSON inline dans le code TypeScript.",
    },
    {
        name: "nodemon",
        icon: "🔄",
        version: "^3.1.11",
        tags: ["dev"],
        short: "Redémarrage automatique du serveur en développement",
        desc: "Surveille les fichiers TypeScript et JSON du dossier src/ et relance automatiquement le serveur à chaque modification sauvegardée. Élimine le redémarrage manuel pendant le développement. Couplé à ts-node pour exécuter TypeScript directement.",
    },
    {
        name: "ts-node",
        icon: "▶️",
        version: "^10.9.2",
        tags: ["dev"],
        short: "Exécution directe de TypeScript sans compilation",
        desc: "Permet d'exécuter des fichiers TypeScript dans Node.js sans compilation préalable vers JavaScript. Utilisé pour le serveur de dev (via nodemon), les scripts de migration (ts-node run-migrations.ts) et les seeds. Indispensable pour un workflow de dev rapide.",
    },
];
